#!/usr/bin/env python3
"""
============================================================
NOVA-X Pull Request Manager v1.0
============================================================

Creates GitHub Pull Requests with explicit human approval.

Workflow:

1. Create feature branch
2. Stage files
3. Commit
4. Push
5. Open GitHub Pull Request

============================================================
"""

import subprocess
import sys
import re


class PullRequestManager:

    def run(self, command):

        return subprocess.run(
            command,
            capture_output=True,
            text=True
        )

    def slug(self, text):

        text = text.lower().strip()
        text = re.sub(r'[^a-z0-9]+', '-', text)
        return text.strip("-")

    def create_pull_request(self, title, body="Generated by NOVA-X"):

        branch = "feature/" + self.slug(title)

        print()
        print("=" * 60)
        print("NOVA-X PULL REQUEST")
        print("=" * 60)

        print("Title :", title)
        print("Branch:", branch)

        print()
        answer = input("Proceed with GitHub Pull Request? (yes/no): ")

        if answer.lower() != "yes":
            print("\nCancelled.")
            return

        print("\nCreating feature branch...")

        r = self.run(["git", "checkout", "-b", branch])

        if r.returncode != 0:

            if "already exists" in r.stderr.lower():

                print("Branch already exists.")
                print("Switching to branch...")

                r = self.run(["git", "checkout", branch])

                if r.returncode != 0:
                    print(r.stderr)
                    return

            else:
                print(r.stderr)
                return

        print("Staging changes...")

        r = self.run(["git", "add", "."])

        if r.returncode != 0:
            print(r.stderr)
            return

        print("Creating commit...")

        r = self.run([
            "git",
            "commit",
            "-m",
            title
        ])

        if r.returncode != 0:

            if "nothing to commit" in r.stderr.lower() or \
               "nothing to commit" in r.stdout.lower():

                print("No modified files.")
                return

            print(r.stderr)
            return

        print("Pushing branch...")

        r = self.run([
            "git",
            "push",
            "-u",
            "origin",
            branch
        ])

        if r.returncode != 0:
            print(r.stderr)
            return

        print("Creating GitHub Pull Request...")

        r = self.run([
            "gh",
            "pr",
            "create",
            "--base",
            "main",
            "--head",
            branch,
            "--title",
            title,
            "--body",
            body
        ])

        if r.returncode != 0:
            print(r.stderr)
            return

        print()
        print("=" * 60)
        print("SUCCESS")
        print("=" * 60)
        print()
        print(r.stdout)


if __name__ == "__main__":

    if len(sys.argv) < 2:

        print()
        print("Usage:")
        print()
        print('python3 pull_request_manager.py "PR Title"')
        sys.exit(1)

    title = sys.argv[1]

    body = "Autonomously proposed by NOVA-X."

    PullRequestManager().create_pull_request(
        title,
        body
    )
