#!/usr/bin/env python3
"""
===========================================================
NOVA-X Tool Generator v1.0
===========================================================

Generates Python class scaffolds from tool specifications.

Author:
Douglas Davis & OpenAI
===========================================================
"""

import os
from tool_architect import ToolArchitect


class ToolGenerator:

    def __init__(self, output_directory="generated_tools"):

        self.output_directory = output_directory

        os.makedirs(self.output_directory, exist_ok=True)

    def generate(self, specification):

        class_name = specification["tool_name"].replace(" ", "")

        filename = (
            class_name.lower() + ".py"
        )

        filepath = os.path.join(
            self.output_directory,
            filename
        )

        with open(filepath, "w") as f:

            f.write('"""\n')
            f.write(f'{class_name}\n')
            f.write('Automatically generated by NOVA-X\n')
            f.write('"""\n\n')

            f.write(f"class {class_name}:\n\n")

            f.write("    def __init__(self):\n")
            f.write("        pass\n\n")

            for method in specification["methods"]:

                name = method.split("(")[0]

                params = method[
                    method.find("(")+1:
                    method.find(")")
                ]

                if params.strip():

                    f.write(
                        f"    def {name}(self, {params}):\n"
                    )

                else:

                    f.write(
                        f"    def {name}(self):\n"
                    )

                f.write(
                    '        """Auto-generated stub."""\n'
                )

                f.write(
                    '        raise NotImplementedError("Method not implemented yet.")\n\n'
                )

        return filepath


############################################################

if __name__ == "__main__":

    architect = ToolArchitect()

    proposal = {

        "name": "PDF Reader",

        "purpose": "Extract text from PDF files.",

        "confidence": 0.95

    }

    specification = architect.design(proposal)

    generator = ToolGenerator()

    path = generator.generate(specification)

    print()

    print("=" * 60)

    print("NOVA-X TOOL GENERATOR")

    print("=" * 60)

    print()

    print("Generated Tool:")

    print(path)

