"""
PDFReader
Automatically generated by NOVA-X
"""

class PDFReader:

    def __init__(self):
        pass

    def load(self, path):
        """Auto-generated stub."""
        raise NotImplementedError("Method not implemented yet.")

    def extract_text(self):
        """Auto-generated stub."""
        raise NotImplementedError("Method not implemented yet.")

    def search(self, query):
        """Auto-generated stub."""
        raise NotImplementedError("Method not implemented yet.")

